export default [
    { id: 1, name: 'John Doe', avatar: 'https://randomuser.me/api/portraits/men/1.jpg',  title: 'Drive me home from Airport', priority: 5, stars: 3, category: 'Grocery deliveries and more', address: 'Tallinn', start_date: '2025-10-01', end_date: '2025-10-05' },
    { id: 2, name: 'Jane Smith', avatar: 'https://randomuser.me/api/portraits/women/2.jpg', title: 'Pick up groceries and essentials', priority: 3, stars: 4, category: 'Grocery deliveries and more', address: 'Tartu', start_date: '2025-09-28', end_date: '2025-10-02' },
    { id: 3, name: 'Alex Johnson', avatar: 'https://randomuser.me/api/portraits/men/3.jpg', title: 'Assemble IKEA furniture', priority: 4, stars: 5, category: 'Home help and maintenance', address: 'Pärnu', start_date: '2025-10-10', end_date: '2025-10-11' },
    { id: 4, name: 'Maria Garcia', avatar: 'https://randomuser.me/api/portraits/women/4.jpg', title: 'Dog walking (daily)', priority: 2, stars: 4, category: 'Pet care and sitting', address: 'Narva', start_date: '2025-10-01', end_date: '2025-10-31' },
    { id: 5, name: 'Liam Brown', avatar: 'https://randomuser.me/api/portraits/men/5.jpg', title: 'Help moving small furniture', priority: 5, stars: 5, category: 'Transportation and moving', address: 'Rakvere', start_date: '2025-11-05', end_date: '2025-11-06' },
    { id: 6, name: 'Eveli Saar', avatar: 'https://randomuser.me/api/portraits/women/6.jpg', title: 'Babysitting for 2 kids (evening)', priority: 4, stars: 5, category: 'Childcare and tutoring', address: 'Viljandi', start_date: '2025-10-18', end_date: '2025-10-18' },
    { id: 7, name: 'Noah Davis', avatar: 'https://randomuser.me/api/portraits/men/7.jpg', title: 'On-site tech support (PC repair)', priority: 3, stars: 3, category: 'Tech and IT help', address: 'Kuressaare', start_date: '2025-09-30', end_date: '2025-10-03' },
    { id: 8, name: 'Liis Kask', avatar: 'https://randomuser.me/api/portraits/women/8.jpg', title: 'Garden maintenance (mowing & weeding)', priority: 2, stars: 4, category: 'Home help and maintenance', address: 'Võru', start_date: '2025-08-20', end_date: '2025-08-21' },
    { id: 9, name: 'Oskar Lepp', avatar: 'https://randomuser.me/api/portraits/men/9.jpg', title: 'Deliver important documents', priority: 5, stars: 5, category: 'Courier and delivery services', address: 'Jõhvi', start_date: '2025-10-05', end_date: '2025-10-05' },
    { id: 10, name: 'Anu Pärn', avatar: 'https://randomuser.me/api/portraits/women/10.jpg', title: 'Event photography (2 hours)', priority: 4, stars: 5, category: 'Creative and media services', address: 'Tallinn', start_date: '2025-12-12', end_date: '2025-12-12' }
]