export default [
    { id: 1, name: 'John Doe', avatar: 'https://randomuser.me/api/portraits/men/1.jpg',  title: 'Drive me home from Airport', priority: 5, stars: 3, category: 'Grocery deliveries and more', address: 'Tallinn', start_date: '2025-10-01', end_date: '2025-10-05' },
    { id: 2, name: 'Jane Smith', avatar: 'https://randomuser.me/api/portraits/women/2.jpg', title: 'Grocery pickup and drop-off', priority: 3, stars: 4, category: 'Grocery deliveries and more', address: 'Tartu', start_date: '2025-09-15', end_date: '2025-09-16' },
    { id: 3, name: 'Carlos Ruiz', avatar: 'https://randomuser.me/api/portraits/men/3.jpg', title: 'Assemble flatpack furniture', priority: 4, stars: 5, category: 'Home help and repairs', address: 'Pärnu', start_date: '2025-08-20', end_date: '2025-08-21' },
    { id: 4, name: 'Aino Laine', avatar: 'https://randomuser.me/api/portraits/women/4.jpg', title: 'Dog walking (daily)', priority: 2, stars: 3, category: 'Pet services', address: 'Narva', start_date: '2025-07-01', end_date: '2025-07-31' },
    { id: 5, name: 'Marco Bianchi', avatar: 'https://randomuser.me/api/portraits/men/5.jpg', title: 'Help moving small apartment', priority: 5, stars: 4, category: 'Moving and transport', address: 'Viljandi', start_date: '2025-06-10', end_date: '2025-06-10' },
    { id: 6, name: 'Li Wei', avatar: 'https://randomuser.me/api/portraits/women/6.jpg', title: 'Babysitting for evening', priority: 3, stars: 5, category: 'Childcare', address: 'Tallinn', start_date: '2025-11-12', end_date: '2025-11-12' },
    { id: 7, name: 'Oleg Petrov', avatar: 'https://randomuser.me/api/portraits/men/7.jpg', title: 'Garden cleanup and planting', priority: 2, stars: 2, category: 'Gardening', address: 'Rakvere', start_date: '2025-05-05', end_date: '2025-05-06' },
    { id: 8, name: 'Marta Nowak', avatar: 'https://randomuser.me/api/portraits/women/8.jpg', title: 'Tech help: set up home Wi‑Fi', priority: 4, stars: 4, category: 'IT and tech support', address: 'Kuressaare', start_date: '2025-04-18', end_date: '2025-04-18' },
    { id: 9, name: 'Samir Khan', avatar: 'https://randomuser.me/api/portraits/men/9.jpg', title: 'Pick up prescription', priority: 1, stars: 3, category: 'Errands', address: 'Jõhvi', start_date: '2025-03-02', end_date: '2025-03-02' },
    { id: 10, name: 'Eva Müller', avatar: 'https://randomuser.me/api/portraits/women/10.jpg', title: 'Language tutoring (Estonian)', priority: 3, stars: 5, category: 'Lessons and tutoring', address: 'Paide', start_date: '2025-12-01', end_date: '2025-12-31' },
    { id: 11, name: 'Liam O\'Connor', avatar: 'https://randomuser.me/api/portraits/men/11.jpg', title: 'Photography for small event', priority: 5, stars: 5, category: 'Events and photography', address: 'Sillamäe', start_date: '2025-09-05', end_date: '2025-09-05' }
]